services:
  - type: web
    name: contratos-cobranca
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m gunicorn app:app --bind 0.0.0.0:$PORT
