services:
  - type: web
    name: contratos-cobranca       # o slug do seu serviço
    env: python                    # força o ambiente Python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py   # use python3 para garantir